"""
DataForge Power Query M Code Generator

Translates DataForge cleaning steps and schema into Power Query M code
that can be pasted directly into Power BI Desktop's Advanced Editor.
"""

from datetime import datetime
from typing import List, Dict, Any, Optional
from pathlib import Path


class MCodeGenerator:
    """Generates Power Query M code from DataForge project data."""

    def __init__(self, table_name: str, dialect: str = 'snowflake'):
        self.table_name = table_name
        self.dialect = dialect
        self.m_code_lines: List[str] = []

    def generate(self, source_file: str, headers: List[str],
                 column_map: Dict[str, str],
                 cleaning_audit: List[Dict[str, Any]],
                 schema_columns: List[Dict[str, Any]]) -> str:
        lines = []

        lines.append(f"// Auto-generated by DataForge v2.0")
        lines.append(f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"// Source File: {Path(source_file).name}")
        lines.append(f"// Table Name: {self.table_name}")
        lines.append(f"// SQL Dialect: {self.dialect}")
        lines.append("")
        lines.append("let")
        lines.append("")

        # Step 1: Source
        lines.append(f"    // Step 1: Load source data")
        lines.append(f"    Source = Csv.Document(File.Contents(\"{source_file}\"),")
        lines.append(f"        [Delimiter=\",\", Columns={len(headers)}, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),")
        lines.append("")

        # Step 2: Promote headers
        lines.append(f"    // Step 2: Promote first row as headers")
        lines.append(f"    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),")
        lines.append("")

        # Step 3: Rename columns
        if column_map:
            lines.append(f"    // Step 3: Standardize column names (from DataForge Column Name Map)")
            rename_pairs = []
            for orig, clean in column_map.items():
                rename_pairs.append(f'        {{"{orig}", "{clean}"}}')
            lines.append(f"    RenamedColumns = Table.RenameColumns(PromotedHeaders,")
            lines.append(f"        {{{chr(10).join(rename_pairs)}")
            lines.append(f"        }}),")
            lines.append("")
            last_step = "RenamedColumns"
        else:
            last_step = "PromotedHeaders"

        # Step 4: Type conversions
        lines.append(f"    // Step 4: Apply data types (from DataForge schema inference)")
        type_pairs = []
        for col in schema_columns:
            clean_name = col['clean_name']
            inferred = col['inferred_type']
            m_type = self._map_to_m_type(inferred)
            type_pairs.append(f'        {{"{clean_name}", {m_type}}}')

        lines.append(f"    TypedColumns = Table.TransformColumnTypes({last_step},")
        lines.append(f"        {{{chr(10).join(type_pairs)}")
        lines.append(f"        }}),")
        lines.append("")

        # Step 5: Cleaning steps
        if cleaning_audit:
            lines.append(f"    // Step 5: Apply cleaning rules (from DataForge audit log)")
            current_step = "TypedColumns"

            for i, action in enumerate(cleaning_audit):
                step_name = f"CleanStep{i + 1}"
                desc = action.get('description', action['action'])
                lines.append(f"    //   {desc}")

                if action['action'] == 'standardize_nulls':
                    lines.append(f"    {step_name} = Table.ReplaceValue({current_step},")
                    lines.append(f"        \"NA\", null, Replacer.ReplaceValue, Table.ColumnNames({current_step})),")
                elif action['action'] == 'strip_whitespace':
                    lines.append(f"    {step_name} = Table.TransformColumns({current_step},")
                    lines.append(f"        List.Transform(Table.ColumnNames({current_step}), each {{_, Text.Trim}})),")
                else:
                    lines.append(f"    {step_name} = {current_step}, // {action['action']}")

                current_step = step_name
                lines.append("")

            last_step = current_step
        else:
            last_step = "TypedColumns"

        lines.append(f"    // Final output")
        lines.append(f"    FinalTable = {last_step}")
        lines.append("")
        lines.append("in")
        lines.append("    FinalTable")

        return "\n".join(lines)

    def _map_to_m_type(self, inferred_type: str) -> str:
        type_map = {
            'integer': 'Int64.Type',
            'float': 'Double.Type',
            'decimal': 'Decimal.Type',
            'boolean': 'Logical.Type',
            'date': 'Date.Type',
            'datetime': 'DateTime.Type',
            'varchar_short': 'Text.Type',
            'varchar': 'Text.Type',
            'text': 'Text.Type',
            'variant': 'Any.Type',
        }
        return type_map.get(inferred_type, 'Any.Type')

    def save_to_file(self, file_path: str, m_code: str):
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(m_code)
