"""
DataForge Power BI Exporter

Exports all Power BI integration artifacts:
- Staged CSV (cleaned, renamed columns)
- Power Query M Code (.pq)
- MERGE SQL (upsert pattern)
- Audit Log (JSON)
- README
"""

import csv
import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

from bi.m_code_generator import MCodeGenerator


class PowerBIExporter:
    """Exports all Power BI artifacts from a DataForge project."""

    def export_all(self, table_name: str, source_file: str,
                   headers: List[str], cleaned_rows: List[List[Any]],
                   column_map: Dict[str, str],
                   cleaning_audit: List[Dict[str, Any]],
                   schema_columns: List[Dict[str, Any]],
                   dialect: str = 'snowflake') -> Dict[str, str]:
        """
        Export all Power BI artifacts.
        Returns dict of artifact_name -> file_path.
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        output_dir = Path.home() / 'Downloads' / f'dataforge_{table_name}_{timestamp}'
        output_dir.mkdir(parents=True, exist_ok=True)

        artifacts = {}

        # 1. Staged CSV
        csv_path = output_dir / f'{table_name}_staged.csv'
        self._export_staged_csv(csv_path, headers, cleaned_rows, column_map)
        artifacts['staged_csv'] = str(csv_path)

        # 2. M Code
        m_path = output_dir / f'{table_name}_query.pq'
        m_gen = MCodeGenerator(table_name, dialect)
        m_code = m_gen.generate(
            source_file=str(csv_path),
            headers=headers,
            column_map=column_map,
            cleaning_audit=cleaning_audit,
            schema_columns=schema_columns
        )
        m_gen.save_to_file(str(m_path), m_code)
        artifacts['m_code'] = str(m_path)

        # 3. MERGE SQL
        merge_path = output_dir / f'{table_name}_merge.sql'
        merge_sql = self._generate_merge_sql(table_name, schema_columns, dialect)
        with open(merge_path, 'w', encoding='utf-8') as f:
            f.write(merge_sql)
        artifacts['merge_sql'] = str(merge_path)

        # 4. Audit Log
        audit_path = output_dir / f'{table_name}_audit.json'
        with open(audit_path, 'w', encoding='utf-8') as f:
            json.dump(cleaning_audit, f, indent=2, default=str)
        artifacts['audit_log'] = str(audit_path)

        # 5. README
        readme_path = output_dir / 'README.md'
        readme = self._generate_readme(table_name, artifacts, dialect)
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme)
        artifacts['readme'] = str(readme_path)

        return artifacts

    def _export_staged_csv(self, file_path: Path, headers: List[str],
                            cleaned_rows: List[List[Any]],
                            column_map: Dict[str, str]):
        clean_headers = [column_map.get(h, h) for h in headers]
        with open(file_path, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(clean_headers)
            for row in cleaned_rows:
                writer.writerow(['' if v is None else str(v) for v in row])

    def _generate_merge_sql(self, table_name: str,
                             schema_columns: List[Dict[str, Any]],
                             dialect: str) -> str:
        pk_cols = [c['clean_name'] for c in schema_columns if c.get('is_pk_candidate')]
        non_pk_cols = [c['clean_name'] for c in schema_columns if not c.get('is_pk_candidate')]
        staging = f'{table_name}_staging'

        lines = [
            f"-- MERGE / UPSERT pattern for {table_name}",
            f"-- Generated by DataForge v2.0",
            f"-- Dialect: {dialect}",
            f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]

        if dialect == 'snowflake':
            lines.append(f"MERGE INTO {table_name} AS target")
            lines.append(f"USING {staging} AS source")
            if pk_cols:
                on_clause = ' AND '.join(f'target.{c} = source.{c}' for c in pk_cols)
                lines.append(f"ON ({on_clause})")
            else:
                lines.append(f"ON (1=0) -- No PK detected; adjust manually")
            lines.append("WHEN MATCHED THEN UPDATE SET")
            if non_pk_cols:
                updates = [f"    target.{c} = source.{c}" for c in non_pk_cols]
                lines.append(',\n'.join(updates))
            lines.append("WHEN NOT MATCHED THEN INSERT")
            all_cols = ', '.join(c['clean_name'] for c in schema_columns)
            all_src = ', '.join(f"source.{c['clean_name']}" for c in schema_columns)
            lines.append(f"    ({all_cols})")
            lines.append(f"    VALUES ({all_src});")
        else:
            lines.append(f"-- MERGE template for {dialect}")
            lines.append(f"-- Adapt syntax as needed for your target database")
            lines.append(f"-- Source staging table: {staging}")
            lines.append(f"-- Target table: {table_name}")

        return '\n'.join(lines)

    def _generate_readme(self, table_name: str, artifacts: Dict[str, str], dialect: str) -> str:
        return f"""# DataForge Export: {table_name}

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Dialect: {dialect}

## Files

| File | Purpose |
|------|---------|
| `{table_name}_staged.csv` | Cleaned & renamed data, ready for Power BI import |
| `{table_name}_query.pq` | Power Query M code — paste into Power BI Advanced Editor |
| `{table_name}_merge.sql` | MERGE/UPSERT SQL for loading to target database |
| `{table_name}_audit.json` | Full cleaning audit trail (JSON) |

## Usage

### Power BI Desktop
1. Open Power BI Desktop
2. Get Data → Text/CSV → select `{table_name}_staged.csv`
3. Or: Transform Data → Advanced Editor → paste contents of `{table_name}_query.pq`

### Database Load
1. Load `{table_name}_staged.csv` to a staging table
2. Run `{table_name}_merge.sql` to upsert into `{table_name}`

Generated by [DataForge](https://github.com/aditcher) — Aaron Ditcher
"""
